apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-to-dev-scaleout
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-dev
  template:
    metadata:
      labels:
        service: nginx-dev
        app: nginx-dev
    spec:
      containers:
      - image: nginx
        name: nginx-to-dev-scaleout
        resources:
          limits:
            cpu: 250m
            memory: 25Mi
          requests:
            cpu: 50m
            memory: 20Mi
