apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-to-dev-scaleout
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-dev
  template:
    metadata:
      labels:
        service: nginx-dev
        app: nginx-dev
    spec:
      containers:
      - image: nginx
        name: nginx-to-dev-scaleout
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 50Mi
